#Contrato do dataset sismico edge
profile_name: seismic_edge_v1
profile_version: 1.0.0

task : binary_anomaly_detection
domain: seismic_edge

#Amostragem e janelamento
sampling_rate : 40.0
window_size: 800
window_seconds: 20.0
step_seconds: 10.0
overlap: 0.5

#labels
normal_label: 0
anomaly_label: 1
normal_name: normal
anomaly_name: fault

#Split principal
#Para o tcc evento e o split principal, mas o formato é flexivel para outros tipos de split
split_name: temporal

#metricas
primary_metric: auc_pr
secondary_metrics: [f1, auc_roc, precision, recall]

#Pipeline pra gerar o dataset
preprocessing:
  offline_pipeline:
    - load_vibration_signal
    - select_channel
    - replace_nan_inf
    - detrend_linear
    - demean
    - zscore_per_window

  edge_pipeline:
    - select_channel
    - detrend_linear
    - demean
    - zscore_per_window

  filtering:
     enabled: false
     type: none
     bandpass_hz: null

  normalization: zscore_per_window

labeling:
  strategy: temporal_degradation
  normal_fraction_end: 0.60
  transition_fraction_start: 0.60
  transition_fraction_end: 0.80
  anomaly_fraction_start: 0.80
  discard_transition: true

#Configuracao embarcada
embedded:
  target: esp32
  runtime: tensorflow_lite_micro
  preprocessing_version: seismic_edge_preproc_v1
  ota_strategy_initial: firmware_full_image
  ota_strategy_future: separate_model_update
